spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/request_db
    username: request_user
    password: request_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  application:
    name: service-request

server:
  port: 8084

logging:
  level:
    root: INFO
    com.companies.serivce_request: DEBUG
services:
  serviceCatalog:
    baseUrl: http://localhost:8083
  investorProfile:
    baseUrl: http://localhost:8082
  companyProfile:
    baseUrl: http://localhost:8081