spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/catalog_db
    username: catalog_user
    password: catalog_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: service-catalog-service
  security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://keycloak:8180/realms/gov
            jwk-set-uri: http://keycloak:8180/realms/gov/protocol/openid-connect/certs


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web: DEBUG
    root: INFO
    com.companies: DEBUG    # adjust to your base package

server:
  port: 8083